name: weather_service_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  flutter_svg: ^2.0.5

  flutter_bloc: ^8.1.1

  json_annotation: ^4.8.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  dio: ^5.3.3

  shared_preferences: ^2.2.2

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  bloc_test: ^9.1.0

  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
  